version: '3.8'

services:
  mycity-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - CEREBRAS_API_KEY=${CEREBRAS_API_KEY}
      - GTFS_API_KEY=${GTFS_API_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: PostgreSQL for data storage
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=mycity
      - POSTGRES_USER=mycity
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mycity123}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data: